name: RustBeds
version: '${project.version}'
main: me.happy.rustbeds.RustBeds
api-version: 1.19
load: STARTUP
authors: [ HappySpleen ]
description: A simple plugin to allow players to choose which bed to respawn into.
website: https://github.com/HappySpleen
permissions:
  rustbeds.skipcooldown:
    description: Allows the player to skip the bed's respawn cooldown
    default: false
  rustbeds.maxcount.*:
    description: Allows to set custom max number of beds (ignores the config)
    default: false
  rustbeds.admin:
    description: Allows admins to view and edit stored beds
    default: op
  multiplebedspawn.skipcooldown:
    description: Legacy alias for rustbeds.skipcooldown
    default: false
  multiplebedspawn.maxcount.*:
    description: Legacy alias for rustbeds.maxcount.*
    default: false
  multiplebedspawn.admin:
    description: Legacy alias for rustbeds.admin
    default: op


